name: data_importer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['3.6.3', '4.1.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure the full repo is cloned

      - name: Debug file existence
        run: ls -la
        shell: bash

      - name: Check for DESCRIPTION file
        run: |
          if [ ! -f "DESCRIPTION" ]; then
            echo "❌ ERROR: DESCRIPTION file is missing!"
            exit 1
          else
            echo "✅ DESCRIPTION file found!"
          fi
        shell: bash

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE, upgrade = "always")
          remotes::install_github("r-lib/rcmdcheck")
        shell: Rscript {0}

      - name: Check package
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error', build_args = c('--no-build-vignettes'))"
