name: data_importer

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        r-version: ['4.4.1']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures full repo history

      - name: Verify repository structure
        run: ls -la  # Debug step to check if DESCRIPTION exists

      - name: Set up R ${{ matrix.r-version }}
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.r-version }}

      - name: Install dependencies
        run: |
          if (!file.exists("DESCRIPTION")) stop("DESCRIPTION file is missing!")  # Debug check
          install.packages(c("remotes", "rcmdcheck"))
          remotes::install_deps(dependencies = TRUE, upgrade = "always")
          remotes::install_github("r-lib/rcmdcheck")
        shell: Rscript {0}

      - name: Check package
        run: Rscript -e "rcmdcheck::rcmdcheck(args = '--no-manual', error_on = 'error', build_args = c('--no-build-vignettes'))"
